# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'

volumes:
  orderer.zillabc.io:

networks:
  internal-peer:
    name: internal-peer

services:

  orderer.zillabc.io:
    container_name: orderer.zillabc.io
    restart: unless-stopped
    image: hyperledger/fabric-orderer:2.2.11
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.zillabc.io:9443
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    # entrypoint: tail -f /dev/null
    command: orderer
    volumes:
        - ../organizations/ordererOrganizations/zillabc.io/orderers/orderer.zillabc.io/msp/:/var/hyperledger/orderer/msp
        - ../organizations/ordererOrganizations/zillabc.io/orderers/orderer.zillabc.io/tls/:/var/hyperledger/orderer/tls
        - orderer.zillabc.io:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
      - 9443:9443
    networks:
      - internal-peer

  ca_orderer:
    image: hyperledger/fabric-ca:1.5.6
    restart: unless-stopped
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:19054
    ports:
      - "9054:9054"
      - "19054:19054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer
    networks:
      - internal-peer

  cert-remover:
    image: alpine
    command: |
      rm -rf organizations/fabric-ca/ordererOrg/msp
      rm -f organizations/fabric-ca/ordererOrg/ca-cert.pem
      rm -f organizations/fabric-ca/ordererOrg/fabric-ca-server.db
      rm -f organizations/fabric-ca/ordererOrg/IssuerPublicKey
      rm -f organizations/fabric-ca/ordererOrg/IssuerRevocationPublicKey
      rm -f organizations/fabric-ca/ordererOrg/tls-cert.pem
      rm -rf organizations/ordererOrganizations
      rm -rf organizations/peerOrganizations
    working_dir: /root
    volumes:
      - ../:/root
    networks:
      - internal-peer